import { useEffect, useState } from "react";
import { useLang } from "../context/LangContext";
import PrognosticCard from "../components/PrognosticCard";
import PaymentModal from "../components/PaymentModal";
import { getPrognostics } from "../lib/store";

// Extracts just "HH:mm" out of the "DD.MM.YYYY HH:mm" format api/matches.js
// returns, since that's all a prediction card needs to show.
function kickoffTime(timeStr) {
  const match = timeStr?.match(/(\d{2}):(\d{2})$/);
  return match ? match[0] : timeStr || "";
}

export default function Prognostics() {
  const { t } = useLang();
  const [selected, setSelected] = useState(null);
  const [adminList, setAdminList] = useState([]);
  const [liveMatches, setLiveMatches] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    getPrognostics().then(setAdminList);
    fetch("/api/matches")
      .then((r) => r.json())
      .then((d) => setLiveMatches(d?.matches || []))
      .catch(() => setLiveMatches([]))
      .finally(() => setLoading(false));
  }, []);

  // Kelvin's manually-curated picks (with real success-rate stats) always
  // come first. Underneath, today's other popular matches are added
  // automatically so the page never sits empty on a day nobody had time to
  // update the admin panel — clicking one still requires payment exactly
  // like before, this only automates *which matches appear*, not the
  // unlock flow.
  const adminTeamPairs = new Set(adminList.map((p) => `${p.teamA}|${p.teamB}`));
  const autoGenerated = liveMatches
    .filter((m) => !adminTeamPairs.has(`${m.home}|${m.away}`))
    .slice(0, 8)
    .map((m) => ({
      id: `auto-${m.id}`,
      championship: m.league,
      teamA: m.home,
      teamB: m.away,
      successRate: null,
      buyers: null,
      expiresAt: kickoffTime(m.time),
      isNew: true,
      auto: true,
    }));

  const all = [...adminList, ...autoGenerated];

  return (
    <div className="container" style={{ padding: "48px 24px 64px" }}>
      <div className="eyebrow">{t.prognostics.title}</div>
      <h1 style={{ fontSize: 32, marginTop: 8, marginBottom: 6 }}>{t.prognostics.title}</h1>
      <p style={{ color: "var(--muted)", marginBottom: 12 }}>{t.prognostics.subtitle}</p>

      <div style={{ background: "var(--gold-soft)", color: "var(--forest-deep)", padding: "10px 16px", borderRadius: 10, display: "inline-block", fontSize: 13.5, fontWeight: 600, marginBottom: 28 }}>
        {t.prognostics.bonus}
      </div>

      {loading && all.length === 0 && (
        <div style={{ padding: "24px 0", display: "flex", justifyContent: "center" }}>
          <div className="spinner" />
        </div>
      )}

      {!loading && all.length === 0 && (
        <div className="card" style={{ padding: 20, textAlign: "center" }}>
          <p style={{ fontSize: 13.5, color: "var(--muted)", margin: 0 }}>
            Aucun match disponible pour l'instant.
          </p>
        </div>
      )}

      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))", gap: 16 }}>
        {all.map((p) => (
          <PrognosticCard key={p.id} prognostic={p} onUnlock={setSelected} />
        ))}
      </div>

      {selected && (
        <PaymentModal
          onClose={() => setSelected(null)}
          itemLabel={`${selected.teamA} vs ${selected.teamB}`}
        />
      )}
    </div>
  );
}
